import type { IssueBoardData } from './types';

export const seedData: IssueBoardData = {
  categories: [
    { id: 'grade-product', label: '강종/제품', description: '강종, 제품, 적용 조건 관련 이슈', order: 1, icon: '🧵' },
    { id: 'investment-project', label: '투자/과제', description: '투자, 과제, 예산, 일정 관련 이슈', order: 2, icon: '📁' },
    { id: 'equipment-test', label: '설비/시험', description: '시험 장비, 분석, Pilot, 점검 관련 이슈', order: 3, icon: '🧪' },
    { id: 'system-operation', label: '제도/운영', description: '운영 기준, 승인 체계, 협업 절차 관련 이슈', order: 4, icon: '🤝' },
  ],
  subtopics: [
    { id: 'hpf', categoryId: 'grade-product', label: 'HPF', order: 1 },
    { id: 'sts', categoryId: 'grade-product', label: 'STS', order: 2 },
    { id: 'electrical-steel', categoryId: 'grade-product', label: '전기강판', order: 3 },
    { id: 'plate', categoryId: 'grade-product', label: '후판', order: 4 },
    { id: 'new-investment', categoryId: 'investment-project', label: '신규 투자', order: 1 },
    { id: 'government-project', categoryId: 'investment-project', label: '국책 과제', order: 2 },
    { id: 'joint-research', categoryId: 'investment-project', label: '공동 연구', order: 3 },
    { id: 'budget-schedule', categoryId: 'investment-project', label: '예산/일정', order: 4 },
    { id: 'test-equipment', categoryId: 'equipment-test', label: '시험 장비', order: 1 },
    { id: 'analysis-request', categoryId: 'equipment-test', label: '분석 의뢰', order: 2 },
    { id: 'pilot', categoryId: 'equipment-test', label: 'Pilot', order: 3 },
    { id: 'safety-inspection', categoryId: 'equipment-test', label: '안전/점검', order: 4 },
    { id: 'operation-standard', categoryId: 'system-operation', label: '운영 기준', order: 1 },
    { id: 'approval-review', categoryId: 'system-operation', label: '심의/승인', order: 2 },
    { id: 'data-security', categoryId: 'system-operation', label: '데이터/보안', order: 3 },
    { id: 'collaboration-process', categoryId: 'system-operation', label: '협업 프로세스', order: 4 },
  ],
  issueGroups: [
    {
      id: 'issue-sts-430-surface',
      title: 'STS-430 표면 결함 재발',
      categoryId: 'grade-product',
      subtopicId: 'sts',
      status: 'resolved',
      statusSource: 'manual',
      firstOccurredAt: '2026-01-01',
      latestUpdatedAt: '2026-02-04',
      currentSummary: '공정 조건 조정 후 2차 샘플에서 재발 없음',
      tags: ['STS-430', '표면결함', '열처리', '고객A'],
      groupLabel: '표면결함개선',
      groupColorTone: 'teal',
      ownerName: '김연구',
      ownerResearchGroup: '표면품질연구그룹',
      relatedDepartment: '냉연품질보증섹션',
      priorityLabel: '보통',
      sensitive: true,
      archived: false,
    },
    {
      id: 'issue-sts-corrosion-test',
      title: 'STS 내식성 시험 조건 이슈',
      categoryId: 'grade-product',
      subtopicId: 'sts',
      status: 'cause_review',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-11',
      latestUpdatedAt: '2026-06-20',
      currentSummary: '시험 조건 편차 원인 검토 중',
      tags: ['STS', '내식성', '시험조건'],
      groupLabel: '시험조건',
      groupColorTone: 'neutral',
      ownerName: '박연구',
      ownerResearchGroup: '스테인리스솔루션그룹',
      relatedDepartment: '분석시험센터',
      priorityLabel: '보통',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-hpf-forming-delay',
      title: 'HPF 성형 조건 검증 지연',
      categoryId: 'grade-product',
      subtopicId: 'hpf',
      status: 'actioning',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-03',
      latestUpdatedAt: '2026-06-24',
      currentSummary: '추가 샘플 확보 후 재검증 예정',
      tags: ['HPF', '성형', '검증'],
      groupLabel: '성형조건',
      groupColorTone: 'green',
      ownerName: '이연구',
      ownerResearchGroup: '성형공정연구그룹',
      relatedDepartment: '열성형기술섹션',
      priorityLabel: '높음',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-operation-approval-delay',
      title: '공동연구 샘플 반출 승인 지연',
      categoryId: 'system-operation',
      subtopicId: 'approval-review',
      status: 'actioning',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-14',
      latestUpdatedAt: '2026-06-21',
      currentSummary: '부서 간 승인 책임 구간 재정의 진행 중',
      tags: ['승인', '공동연구', '샘플반출'],
      groupLabel: '승인흐름',
      groupColorTone: 'neutral',
      ownerName: '정연구',
      ownerResearchGroup: '연구운영기획그룹',
      relatedDepartment: '법무/보안검토파트',
      priorityLabel: '높음',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-electrical-core-loss',
      title: '전기강판 철손 편차 재점검',
      categoryId: 'grade-product',
      subtopicId: 'electrical-steel',
      status: 'verification',
      statusSource: 'auto',
      firstOccurredAt: '2026-05-18',
      latestUpdatedAt: '2026-06-18',
      currentSummary: '측정 조건 보정 후 반복성 확인 중',
      tags: ['전기강판', '철손', '측정조건'],
      groupLabel: '성능편차',
      groupColorTone: 'teal',
      ownerName: '문연구',
      ownerResearchGroup: '전기강판솔루션그룹',
      relatedDepartment: '전기강판품질섹션',
      priorityLabel: '보통',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-plate-ultrasonic',
      title: '후판 초음파 탐상 재검 일정 조정',
      categoryId: 'grade-product',
      subtopicId: 'plate',
      status: 'on_hold',
      statusSource: 'auto',
      firstOccurredAt: '2026-04-29',
      latestUpdatedAt: '2026-06-12',
      currentSummary: '고객 입회 일정 확정 대기',
      tags: ['후판', '초음파탐상', '고객입회'],
      groupLabel: '검사일정',
      groupColorTone: 'neutral',
      ownerName: '최연구',
      ownerResearchGroup: '후판응용연구그룹',
      relatedDepartment: '후판품질보증섹션',
      priorityLabel: '보통',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-investment-pilot-furnace',
      title: 'Pilot 열처리로 증설 투자 검토',
      categoryId: 'investment-project',
      subtopicId: 'new-investment',
      status: 'cause_review',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-07',
      latestUpdatedAt: '2026-06-22',
      currentSummary: '수요 부서별 사용률 재산정 중',
      tags: ['투자검토', 'Pilot', '열처리로'],
      groupLabel: '투자검토',
      groupColorTone: 'green',
      ownerName: '한연구',
      ownerResearchGroup: '투자과제기획그룹',
      relatedDepartment: '설비투자검토파트',
      priorityLabel: '높음',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-government-hydrogen',
      title: '수소환원 국책 과제 산출물 정합성 점검',
      categoryId: 'investment-project',
      subtopicId: 'government-project',
      status: 'actioning',
      statusSource: 'auto',
      firstOccurredAt: '2026-05-30',
      latestUpdatedAt: '2026-06-19',
      currentSummary: '기관별 제출 양식 차이 조정 중',
      tags: ['국책과제', '수소환원', '산출물'],
      groupLabel: '과제관리',
      groupColorTone: 'teal',
      ownerName: '서연구',
      ownerResearchGroup: '미래공정연구그룹',
      relatedDepartment: '과제관리섹션',
      priorityLabel: '높음',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-joint-research-nda',
      title: '공동 연구 NDA 검토 지연',
      categoryId: 'investment-project',
      subtopicId: 'joint-research',
      status: 'occurred',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-23',
      latestUpdatedAt: '2026-06-23',
      currentSummary: '상대 기관 수정 조항 접수',
      tags: ['공동연구', 'NDA', '법무검토'],
      groupLabel: '계약검토',
      groupColorTone: 'neutral',
      ownerName: '정연구',
      ownerResearchGroup: '연구운영기획그룹',
      relatedDepartment: '법무검토파트',
      priorityLabel: '보통',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-budget-q3-adjustment',
      title: '3분기 시험비 예산 배분 조정',
      categoryId: 'investment-project',
      subtopicId: 'budget-schedule',
      status: 'resolved',
      statusSource: 'manual',
      firstOccurredAt: '2026-05-02',
      latestUpdatedAt: '2026-06-05',
      currentSummary: '우선순위 조정안 확정',
      tags: ['예산', '시험비', '일정'],
      groupLabel: '예산조정',
      groupColorTone: 'green',
      ownerName: '오연구',
      ownerResearchGroup: '투자과제기획그룹',
      relatedDepartment: '예산운영파트',
      priorityLabel: '보통',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-equipment-salt-spray',
      title: '염수분무 시험기 교정 주기 조정',
      categoryId: 'equipment-test',
      subtopicId: 'test-equipment',
      status: 'verification',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-01',
      latestUpdatedAt: '2026-06-25',
      currentSummary: '교정 후 기준 시편 반복성 확인',
      tags: ['시험장비', '염수분무', '교정'],
      groupLabel: '장비교정',
      groupColorTone: 'teal',
      ownerName: '배연구',
      ownerResearchGroup: '시험분석연구그룹',
      relatedDepartment: '분석시험센터',
      priorityLabel: '높음',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-analysis-fracture',
      title: '파단면 분석 의뢰 병목',
      categoryId: 'equipment-test',
      subtopicId: 'analysis-request',
      status: 'actioning',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-09',
      latestUpdatedAt: '2026-06-17',
      currentSummary: '우선순위 기준표로 의뢰 순서 재정렬',
      tags: ['분석의뢰', '파단면', 'SEM'],
      groupLabel: '분석대기',
      groupColorTone: 'neutral',
      ownerName: '남연구',
      ownerResearchGroup: '분석기술연구그룹',
      relatedDepartment: '전자현미경실',
      priorityLabel: '높음',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-pilot-cooling-water',
      title: 'Pilot 냉각수 유량 이상 감지',
      categoryId: 'equipment-test',
      subtopicId: 'pilot',
      status: 'cause_review',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-16',
      latestUpdatedAt: '2026-06-24',
      currentSummary: '밸브 개도와 센서 로그 대조 중',
      tags: ['Pilot', '냉각수', '센서'],
      groupLabel: '운전조건',
      groupColorTone: 'teal',
      ownerName: '강연구',
      ownerResearchGroup: 'Pilot운영그룹',
      relatedDepartment: '설비보전섹션',
      priorityLabel: '보통',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-safety-gas-alarm',
      title: '가스 감지기 점검 결과 공유 지연',
      categoryId: 'equipment-test',
      subtopicId: 'safety-inspection',
      status: 'resolved',
      statusSource: 'manual',
      firstOccurredAt: '2026-05-24',
      latestUpdatedAt: '2026-06-13',
      currentSummary: '월간 점검 공유 루틴 확정',
      tags: ['안전점검', '가스감지기', '공유'],
      groupLabel: '안전점검',
      groupColorTone: 'green',
      ownerName: '신연구',
      ownerResearchGroup: '시험분석연구그룹',
      relatedDepartment: '안전환경섹션',
      priorityLabel: '보통',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-standard-test-request',
      title: '시험 의뢰 기준 개정 논의',
      categoryId: 'system-operation',
      subtopicId: 'operation-standard',
      status: 'verification',
      statusSource: 'auto',
      firstOccurredAt: '2026-05-14',
      latestUpdatedAt: '2026-06-10',
      currentSummary: '개정안 공지 후 현장 적용성 확인 중',
      tags: ['운영기준', '시험의뢰', '개정'],
      groupLabel: '제도개선',
      groupColorTone: 'teal',
      ownerName: '윤연구',
      ownerResearchGroup: '연구운영기획그룹',
      relatedDepartment: '시험접수데스크',
      priorityLabel: '보통',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-data-retention',
      title: '시험 데이터 보존 정책 정리',
      categoryId: 'system-operation',
      subtopicId: 'data-security',
      status: 'actioning',
      statusSource: 'auto',
      firstOccurredAt: '2026-05-27',
      latestUpdatedAt: '2026-06-18',
      currentSummary: '민감 데이터 보존 기간 기준 조율 중',
      tags: ['데이터보안', '보존정책', '내부전용'],
      groupLabel: '보안정책',
      groupColorTone: 'neutral',
      ownerName: '임연구',
      ownerResearchGroup: '연구데이터관리그룹',
      relatedDepartment: '정보보호파트',
      priorityLabel: '높음',
      sensitive: true,
      archived: false,
    },
    {
      id: 'issue-collaboration-weekly',
      title: '협업 과제 주간 공유 루틴 정착',
      categoryId: 'system-operation',
      subtopicId: 'collaboration-process',
      status: 'resolved',
      statusSource: 'manual',
      firstOccurredAt: '2026-04-18',
      latestUpdatedAt: '2026-06-07',
      currentSummary: '금요일 15시 공유 루틴 고정',
      tags: ['협업', '주간공유', '운영루틴'],
      groupLabel: '협업프로세스',
      groupColorTone: 'green',
      ownerName: '조연구',
      ownerResearchGroup: '연구운영기획그룹',
      relatedDepartment: '전략협업섹션',
      priorityLabel: '보통',
      sensitive: false,
      archived: false,
    },
  ],
  detailIssues: [
    {
      id: 'detail-sts-430-rolling-recur',
      issueGroupId: 'issue-sts-430-surface',
      title: '압연 조건 변경 후 재발 확인',
      status: 'resolved',
      firstOccurredAt: '2026-01-01',
      latestUpdatedAt: '2026-02-04',
      currentSummary: '조건 조정 후 2차 샘플에서 재발 없음',
      tags: ['압연조건', '재발확인'],
      relatedEquipment: '열연 #2',
      relatedCustomer: '고객A',
      priorityLabel: '보통',
      ownerName: '김연구',
      ownerResearchGroup: '표면품질연구그룹',
      relatedDepartment: '냉연품질보증섹션',
      completedAt: '2026-02-04',
      completionNote: '최종 조건 조정 후 재발 없음 확인',
      archived: false,
    },
    {
      id: 'detail-sts-corrosion-test-condition',
      issueGroupId: 'issue-sts-corrosion-test',
      title: '염수 분무 조건 편차 확인',
      status: 'cause_review',
      firstOccurredAt: '2026-06-20',
      latestUpdatedAt: '2026-06-20',
      currentSummary: '시편 준비 조건과 장비 설정값 비교 중',
      tags: ['시험조건', '내식성'],
      ownerName: '박연구',
      ownerResearchGroup: '스테인리스솔루션그룹',
      relatedDepartment: '분석시험센터',
      priorityLabel: '보통',
      needsReview: false,
      archived: false,
    },
    {
      id: 'detail-operation-approval-role',
      issueGroupId: 'issue-operation-approval-delay',
      title: '샘플 반출 승인 책임 구간 불명확',
      status: 'actioning',
      firstOccurredAt: '2026-06-14',
      latestUpdatedAt: '2026-06-21',
      currentSummary: '승인 책임과 보안 검토 선후 관계 조정 중',
      tags: ['승인', '보안검토'],
      priorityLabel: '높음',
      ownerName: '정연구',
      ownerResearchGroup: '연구운영기획그룹',
      relatedDepartment: '법무/보안검토파트',
      needsReview: true,
      archived: false,
    },
    {
      id: 'detail-electrical-core-loss-repeatability',
      issueGroupId: 'issue-electrical-core-loss',
      title: '철손 측정 반복성 확인',
      status: 'verification',
      firstOccurredAt: '2026-05-18',
      latestUpdatedAt: '2026-06-18',
      currentSummary: '측정 조건 보정 후 반복성 확인 중',
      tags: ['철손', '반복성'],
      relatedEquipment: '자기특성 측정기 #1',
      priorityLabel: '보통',
      ownerName: '문연구',
      ownerResearchGroup: '전기강판솔루션그룹',
      relatedDepartment: '전기강판품질섹션',
      archived: false,
    },
    {
      id: 'detail-plate-ultrasonic-witness',
      issueGroupId: 'issue-plate-ultrasonic',
      title: '고객 입회 재검 일정 조율',
      status: 'on_hold',
      firstOccurredAt: '2026-04-29',
      latestUpdatedAt: '2026-06-12',
      currentSummary: '고객 입회 일정 확정 대기',
      tags: ['고객입회', '재검'],
      relatedCustomer: '조선 고객B',
      priorityLabel: '보통',
      ownerName: '최연구',
      ownerResearchGroup: '후판응용연구그룹',
      relatedDepartment: '후판품질보증섹션',
      needsReview: true,
      archived: false,
    },
    {
      id: 'detail-investment-pilot-furnace-demand',
      issueGroupId: 'issue-investment-pilot-furnace',
      title: '부서별 Pilot 열처리 수요 재산정',
      status: 'cause_review',
      firstOccurredAt: '2026-06-07',
      latestUpdatedAt: '2026-06-22',
      currentSummary: '수요 부서별 사용률 재산정 중',
      tags: ['수요조사', '투자검토'],
      priorityLabel: '높음',
      ownerName: '한연구',
      ownerResearchGroup: '투자과제기획그룹',
      relatedDepartment: '설비투자검토파트',
      archived: false,
    },
    {
      id: 'detail-government-hydrogen-deliverable',
      issueGroupId: 'issue-government-hydrogen',
      title: '기관별 산출물 양식 정합성',
      status: 'actioning',
      firstOccurredAt: '2026-05-30',
      latestUpdatedAt: '2026-06-19',
      currentSummary: '기관별 제출 양식 차이 조정 중',
      tags: ['산출물', '정합성'],
      priorityLabel: '높음',
      ownerName: '서연구',
      ownerResearchGroup: '미래공정연구그룹',
      relatedDepartment: '과제관리섹션',
      archived: false,
    },
    {
      id: 'detail-joint-research-nda-clause',
      issueGroupId: 'issue-joint-research-nda',
      title: 'NDA 수정 조항 법무 검토',
      status: 'occurred',
      firstOccurredAt: '2026-06-23',
      latestUpdatedAt: '2026-06-23',
      currentSummary: '상대 기관 수정 조항 접수',
      tags: ['NDA', '법무'],
      priorityLabel: '보통',
      ownerName: '정연구',
      ownerResearchGroup: '연구운영기획그룹',
      relatedDepartment: '법무검토파트',
      needsReview: true,
      archived: false,
    },
    {
      id: 'detail-budget-q3-test-cost',
      issueGroupId: 'issue-budget-q3-adjustment',
      title: '3분기 시험비 우선순위 조정',
      status: 'resolved',
      firstOccurredAt: '2026-05-02',
      latestUpdatedAt: '2026-06-05',
      currentSummary: '우선순위 조정안 확정',
      tags: ['시험비', '우선순위'],
      priorityLabel: '보통',
      ownerName: '오연구',
      ownerResearchGroup: '투자과제기획그룹',
      relatedDepartment: '예산운영파트',
      completedAt: '2026-06-05',
      completionNote: 'Q3 시험비 조정안 확정',
      archived: false,
    },
    {
      id: 'detail-equipment-salt-spray-calibration',
      issueGroupId: 'issue-equipment-salt-spray',
      title: '교정 후 기준 시편 반복성 확인',
      status: 'verification',
      firstOccurredAt: '2026-06-01',
      latestUpdatedAt: '2026-06-25',
      currentSummary: '교정 후 기준 시편 반복성 확인',
      tags: ['교정', '기준시편'],
      relatedEquipment: '염수분무 시험기 #2',
      priorityLabel: '높음',
      ownerName: '배연구',
      ownerResearchGroup: '시험분석연구그룹',
      relatedDepartment: '분석시험센터',
      archived: false,
    },
    {
      id: 'detail-analysis-fracture-priority',
      issueGroupId: 'issue-analysis-fracture',
      title: '파단면 분석 우선순위 재정렬',
      status: 'actioning',
      firstOccurredAt: '2026-06-09',
      latestUpdatedAt: '2026-06-17',
      currentSummary: '우선순위 기준표로 의뢰 순서 재정렬',
      tags: ['SEM', '우선순위'],
      relatedEquipment: 'SEM #3',
      priorityLabel: '높음',
      ownerName: '남연구',
      ownerResearchGroup: '분석기술연구그룹',
      relatedDepartment: '전자현미경실',
      archived: false,
    },
    {
      id: 'detail-pilot-cooling-water-log',
      issueGroupId: 'issue-pilot-cooling-water',
      title: '냉각수 유량 로그 이상 대조',
      status: 'cause_review',
      firstOccurredAt: '2026-06-16',
      latestUpdatedAt: '2026-06-24',
      currentSummary: '밸브 개도와 센서 로그 대조 중',
      tags: ['유량로그', '센서'],
      relatedEquipment: 'Pilot 냉각수 라인',
      priorityLabel: '보통',
      ownerName: '강연구',
      ownerResearchGroup: 'Pilot운영그룹',
      relatedDepartment: '설비보전섹션',
      archived: false,
    },
    {
      id: 'detail-safety-gas-alarm-share',
      issueGroupId: 'issue-safety-gas-alarm',
      title: '가스 감지기 점검 공유 루틴',
      status: 'resolved',
      firstOccurredAt: '2026-05-24',
      latestUpdatedAt: '2026-06-13',
      currentSummary: '월간 점검 공유 루틴 확정',
      tags: ['점검공유', '안전'],
      priorityLabel: '보통',
      ownerName: '신연구',
      ownerResearchGroup: '시험분석연구그룹',
      relatedDepartment: '안전환경섹션',
      completedAt: '2026-06-13',
      completionNote: '월간 공유 루틴 확정',
      archived: false,
    },
    {
      id: 'detail-standard-test-request-revision',
      issueGroupId: 'issue-standard-test-request',
      title: '시험 의뢰 기준 개정안 적용성 확인',
      status: 'verification',
      firstOccurredAt: '2026-05-14',
      latestUpdatedAt: '2026-06-10',
      currentSummary: '개정안 공지 후 현장 적용성 확인 중',
      tags: ['시험의뢰', '개정안'],
      priorityLabel: '보통',
      ownerName: '윤연구',
      ownerResearchGroup: '연구운영기획그룹',
      relatedDepartment: '시험접수데스크',
      archived: false,
    },
    {
      id: 'detail-data-retention-sensitive',
      issueGroupId: 'issue-data-retention',
      title: '민감 데이터 보존 기간 기준',
      status: 'actioning',
      firstOccurredAt: '2026-05-27',
      latestUpdatedAt: '2026-06-18',
      currentSummary: '민감 데이터 보존 기간 기준 조율 중',
      tags: ['민감데이터', '보존기간'],
      priorityLabel: '높음',
      ownerName: '임연구',
      ownerResearchGroup: '연구데이터관리그룹',
      relatedDepartment: '정보보호파트',
      needsReview: true,
      archived: false,
    },
    {
      id: 'detail-collaboration-weekly-routine',
      issueGroupId: 'issue-collaboration-weekly',
      title: '협업 과제 주간 공유 루틴',
      status: 'resolved',
      firstOccurredAt: '2026-04-18',
      latestUpdatedAt: '2026-06-07',
      currentSummary: '금요일 15시 공유 루틴 고정',
      tags: ['주간공유', '협업루틴'],
      priorityLabel: '보통',
      ownerName: '조연구',
      ownerResearchGroup: '연구운영기획그룹',
      relatedDepartment: '전략협업섹션',
      completedAt: '2026-06-07',
      completionNote: '정기 공유 루틴 정착',
      archived: false,
    },
  ],
  historyEntries: [
    {
      id: 'hist-sts-430-occurred',
      issueGroupId: 'issue-sts-430-surface',
      detailIssueId: 'detail-sts-430-rolling-recur',
      date: '2026-01-01',
      status: 'occurred',
      changesDetailIssueStatus: true,
      summary: '고객 클레임 접수',
      details: 'STS-430 적용 제품에서 표면 결함 재발 클레임이 접수되었다.',
      remainingRisk: '발생 범위와 재현 조건 확인 필요',
      nextCheckDate: '2026-01-10',
      blockName: '발생 및 접수',
      referenceLinks: [],
      createdAt: '2026-01-01T09:00:00+09:00',
      updatedAt: '2026-01-01T09:00:00+09:00',
    },
    {
      id: 'hist-sts-430-cause',
      issueGroupId: 'issue-sts-430-surface',
      detailIssueId: 'detail-sts-430-rolling-recur',
      date: '2026-01-10',
      status: 'cause_review',
      changesDetailIssueStatus: true,
      summary: '열처리 이력 및 과거 사례 확인',
      details: '동일 강종 과거 사례와 열처리 조건 이력을 대조했다.',
      remainingRisk: '압연 조건 영향 여부 추가 확인 필요',
      nextCheckDate: '2026-01-22',
      blockName: '원인검토',
      referenceLinks: [],
      createdAt: '2026-01-10T10:00:00+09:00',
      updatedAt: '2026-01-10T10:00:00+09:00',
    },
    {
      id: 'hist-sts-430-action',
      issueGroupId: 'issue-sts-430-surface',
      detailIssueId: 'detail-sts-430-rolling-recur',
      date: '2026-01-22',
      status: 'actioning',
      changesDetailIssueStatus: true,
      summary: '임시 조건 조정, 2차 샘플 대기',
      details: '공정 조건을 임시 조정하고 2차 샘플 결과를 기다린다.',
      remainingRisk: '2차 샘플에서 재발 시 추가 조건 변경 필요',
      nextCheckDate: '2026-02-04',
      blockName: '조치 및 검증',
      referenceLinks: [],
      createdAt: '2026-01-22T14:00:00+09:00',
      updatedAt: '2026-01-22T14:00:00+09:00',
    },
    {
      id: 'hist-sts-430-resolved',
      issueGroupId: 'issue-sts-430-surface',
      detailIssueId: 'detail-sts-430-rolling-recur',
      date: '2026-02-04',
      status: 'resolved',
      changesDetailIssueStatus: true,
      summary: '최종 조건 조정 후 재발 없음',
      details: '최종 조건 조정 후 2차 샘플에서 표면 결함 재발이 확인되지 않았다.',
      remainingRisk: '양산 적용 초기 모니터링 필요',
      blockName: '조치 및 검증',
      referenceLinks: [],
      createdAt: '2026-02-04T16:00:00+09:00',
      updatedAt: '2026-02-04T16:00:00+09:00',
    },
    {
      id: 'hist-sts-corrosion-review',
      issueGroupId: 'issue-sts-corrosion-test',
      detailIssueId: 'detail-sts-corrosion-test-condition',
      date: '2026-06-20',
      status: 'cause_review',
      changesDetailIssueStatus: true,
      summary: '시험 조건 편차 원인 검토',
      details: '시편 준비 조건과 시험 장비 설정값을 비교하고 있다.',
      remainingRisk: '동일 조건 반복 시험 필요',
      nextCheckDate: '2026-06-28',
      blockName: '원인검토',
      referenceLinks: ['https://poslab.example/reports/sts-corrosion-test-condition'],
      createdAt: '2026-06-20T11:00:00+09:00',
      updatedAt: '2026-06-20T11:00:00+09:00',
    },
    {
      id: 'hist-operation-approval-delay',
      issueGroupId: 'issue-operation-approval-delay',
      detailIssueId: 'detail-operation-approval-role',
      date: '2026-06-21',
      status: 'actioning',
      changesDetailIssueStatus: true,
      summary: '승인 책임 구간 재정의 진행',
      details: '공동연구 샘플 반출 건에서 연구부서, 보안 검토, 법무 검토의 승인 순서가 중복되어 처리 기간이 길어졌다.',
      remainingRisk: '긴급 반출 건에서 동일 지연이 반복될 수 있음',
      nextCheckDate: '2026-06-27',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '정연구',
      createdAt: '2026-06-21T15:00:00+09:00',
      updatedAt: '2026-06-21T15:00:00+09:00',
    },
    {
      id: 'hist-electrical-core-loss-review',
      issueGroupId: 'issue-electrical-core-loss',
      detailIssueId: 'detail-electrical-core-loss-repeatability',
      date: '2026-06-18',
      status: 'verification',
      changesDetailIssueStatus: true,
      summary: '측정 조건 보정 후 반복성 확인',
      details: '시편 온도 안정화 시간을 늘리고 동일 코일에서 3회 반복 측정을 진행했다.',
      remainingRisk: '다른 두께 샘플에서도 같은 보정 기준 적용 가능성 확인 필요',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '문연구',
      createdAt: '2026-06-18T13:20:00+09:00',
      updatedAt: '2026-06-18T13:20:00+09:00',
    },
    {
      id: 'hist-plate-ultrasonic-hold',
      issueGroupId: 'issue-plate-ultrasonic',
      detailIssueId: 'detail-plate-ultrasonic-witness',
      date: '2026-06-12',
      status: 'on_hold',
      changesDetailIssueStatus: true,
      summary: '고객 입회 일정 확정 대기',
      details: '초음파 탐상 재검 조건은 정리되었으나 고객 입회 가능일이 확정되지 않았다.',
      remainingRisk: '입회 일정 지연 시 출하 판정 일정 영향 가능',
      blockName: '일정 보류',
      referenceLinks: [],
      authorName: '최연구',
      createdAt: '2026-06-12T10:10:00+09:00',
      updatedAt: '2026-06-12T10:10:00+09:00',
    },
    {
      id: 'hist-investment-pilot-furnace-demand',
      issueGroupId: 'issue-investment-pilot-furnace',
      detailIssueId: 'detail-investment-pilot-furnace-demand',
      date: '2026-06-22',
      status: 'cause_review',
      changesDetailIssueStatus: true,
      summary: '부서별 사용률 재산정',
      details: '최근 6개월 Pilot 열처리로 예약률과 취소율을 부서별로 다시 집계했다.',
      remainingRisk: '중복 예약을 제외한 실사용률 기준 합의 필요',
      nextCheckDate: '2026-06-29',
      blockName: '원인검토',
      referenceLinks: [],
      authorName: '한연구',
      createdAt: '2026-06-22T09:40:00+09:00',
      updatedAt: '2026-06-22T09:40:00+09:00',
    },
    {
      id: 'hist-government-hydrogen-format',
      issueGroupId: 'issue-government-hydrogen',
      detailIssueId: 'detail-government-hydrogen-deliverable',
      date: '2026-06-19',
      status: 'actioning',
      changesDetailIssueStatus: true,
      summary: '기관별 제출 양식 차이 조정',
      details: '참여 기관별 산출물 표지와 성과 지표 양식이 달라 통합 제출본 기준을 다시 맞췄다.',
      remainingRisk: '최종 취합 전 버전 혼선 방지 필요',
      nextCheckDate: '2026-06-26',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '서연구',
      createdAt: '2026-06-19T16:30:00+09:00',
      updatedAt: '2026-06-19T16:30:00+09:00',
    },
    {
      id: 'hist-joint-research-nda-received',
      issueGroupId: 'issue-joint-research-nda',
      detailIssueId: 'detail-joint-research-nda-clause',
      date: '2026-06-23',
      status: 'occurred',
      changesDetailIssueStatus: true,
      summary: '상대 기관 NDA 수정 조항 접수',
      details: '공동 연구 착수 전 상대 기관에서 결과물 소유권 관련 수정 조항을 전달했다.',
      remainingRisk: '법무 검토 전 샘플 공유 범위 제한 필요',
      nextCheckDate: '2026-06-27',
      blockName: '발생 및 접수',
      referenceLinks: [],
      authorName: '정연구',
      createdAt: '2026-06-23T11:00:00+09:00',
      updatedAt: '2026-06-23T11:00:00+09:00',
    },
    {
      id: 'hist-budget-q3-fixed',
      issueGroupId: 'issue-budget-q3-adjustment',
      detailIssueId: 'detail-budget-q3-test-cost',
      date: '2026-06-05',
      status: 'resolved',
      changesDetailIssueStatus: true,
      summary: '3분기 시험비 조정안 확정',
      details: '긴급 분석과 고객 대응 시험을 우선 배정하고 장기 검토 과제는 4분기로 이월했다.',
      remainingRisk: '월말 소진률만 추적하면 됨',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '오연구',
      createdAt: '2026-06-05T15:20:00+09:00',
      updatedAt: '2026-06-05T15:20:00+09:00',
    },
    {
      id: 'hist-equipment-salt-spray-verify',
      issueGroupId: 'issue-equipment-salt-spray',
      detailIssueId: 'detail-equipment-salt-spray-calibration',
      date: '2026-06-25',
      status: 'verification',
      changesDetailIssueStatus: true,
      summary: '기준 시편 반복성 확인',
      details: '교정 완료 후 기준 시편 5개를 동일 조건으로 재시험했다.',
      remainingRisk: '야간 운전 조건에서도 편차 재확인 필요',
      nextCheckDate: '2026-07-01',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '배연구',
      createdAt: '2026-06-25T12:00:00+09:00',
      updatedAt: '2026-06-25T12:00:00+09:00',
    },
    {
      id: 'hist-analysis-fracture-priority',
      issueGroupId: 'issue-analysis-fracture',
      detailIssueId: 'detail-analysis-fracture-priority',
      date: '2026-06-17',
      status: 'actioning',
      changesDetailIssueStatus: true,
      summary: '분석 의뢰 우선순위 기준표 적용',
      details: '고객 대응, 안전 관련, 공정 중단 영향 순으로 분석 의뢰 우선순위 기준표를 임시 적용했다.',
      remainingRisk: '급행 의뢰가 늘어날 경우 일반 과제 대기 기간 증가 가능',
      nextCheckDate: '2026-06-24',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '남연구',
      createdAt: '2026-06-17T14:10:00+09:00',
      updatedAt: '2026-06-17T14:10:00+09:00',
    },
    {
      id: 'hist-pilot-cooling-water-review',
      issueGroupId: 'issue-pilot-cooling-water',
      detailIssueId: 'detail-pilot-cooling-water-log',
      date: '2026-06-24',
      status: 'cause_review',
      changesDetailIssueStatus: true,
      summary: '밸브 개도와 센서 로그 대조',
      details: '운전 중 냉각수 유량 저하 알림이 발생해 밸브 개도 기록과 센서 로그를 대조하고 있다.',
      remainingRisk: '센서 오차가 아니면 배관 세정 일정 반영 필요',
      nextCheckDate: '2026-06-30',
      blockName: '원인검토',
      referenceLinks: [],
      authorName: '강연구',
      createdAt: '2026-06-24T17:00:00+09:00',
      updatedAt: '2026-06-24T17:00:00+09:00',
    },
    {
      id: 'hist-safety-gas-alarm-share',
      issueGroupId: 'issue-safety-gas-alarm',
      detailIssueId: 'detail-safety-gas-alarm-share',
      date: '2026-06-13',
      status: 'resolved',
      changesDetailIssueStatus: true,
      summary: '월간 점검 공유 루틴 확정',
      details: '가스 감지기 점검 결과를 월간 안전 공유 메일에 포함하기로 확정했다.',
      remainingRisk: '분기별 누락 여부만 확인',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '신연구',
      createdAt: '2026-06-13T09:30:00+09:00',
      updatedAt: '2026-06-13T09:30:00+09:00',
    },
    {
      id: 'hist-standard-test-request-notice',
      issueGroupId: 'issue-standard-test-request',
      detailIssueId: 'detail-standard-test-request-revision',
      date: '2026-06-10',
      status: 'verification',
      changesDetailIssueStatus: true,
      summary: '개정안 공지 후 적용성 확인',
      details: '시험 의뢰 필수 항목과 긴급 의뢰 기준을 정리해 공지했다.',
      remainingRisk: '현장 입력 누락 사례가 줄었는지 2주간 확인 필요',
      nextCheckDate: '2026-06-28',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '윤연구',
      createdAt: '2026-06-10T10:40:00+09:00',
      updatedAt: '2026-06-10T10:40:00+09:00',
    },
    {
      id: 'hist-data-retention-policy',
      issueGroupId: 'issue-data-retention',
      detailIssueId: 'detail-data-retention-sensitive',
      date: '2026-06-18',
      status: 'actioning',
      changesDetailIssueStatus: true,
      summary: '민감 데이터 보존 기간 기준 조율',
      details: '시험 원자료와 분석 리포트의 보존 기간을 민감도에 따라 나누는 안을 검토했다.',
      remainingRisk: '보안 기준과 연구 재현성 요구가 충돌하는 항목 정리 필요',
      nextCheckDate: '2026-06-27',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '임연구',
      createdAt: '2026-06-18T15:50:00+09:00',
      updatedAt: '2026-06-18T15:50:00+09:00',
    },
    {
      id: 'hist-collaboration-weekly-fixed',
      issueGroupId: 'issue-collaboration-weekly',
      detailIssueId: 'detail-collaboration-weekly-routine',
      date: '2026-06-07',
      status: 'resolved',
      changesDetailIssueStatus: true,
      summary: '금요일 15시 공유 루틴 고정',
      details: '협업 과제 주간 공유 시간을 금요일 15시로 고정하고 담당자별 3줄 요약 양식을 적용했다.',
      remainingRisk: '신규 참여 과제 온보딩 시 양식 안내 필요',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '조연구',
      createdAt: '2026-06-07T15:00:00+09:00',
      updatedAt: '2026-06-07T15:00:00+09:00',
    },
  ],
};
