import type { IssueBoardData } from './types';

export const seedData: IssueBoardData = {
  categories: [
    { id: 'grade-product', label: '강종/제품', description: '강종, 제품, 적용 조건 관련 이슈', order: 1 },
    { id: 'investment-project', label: '투자/과제', description: '투자, 과제, 예산, 일정 관련 이슈', order: 2 },
    { id: 'equipment-test', label: '설비/시험', description: '시험 장비, 분석, Pilot, 점검 관련 이슈', order: 3 },
    { id: 'system-operation', label: '제도/운영', description: '운영 기준, 승인 체계, 협업 절차 관련 이슈', order: 4 },
  ],
  subtopics: [
    { id: 'hpf', categoryId: 'grade-product', label: 'HPF', order: 1 },
    { id: 'sts', categoryId: 'grade-product', label: 'STS', order: 2 },
    { id: 'electrical-steel', categoryId: 'grade-product', label: '전기강판', order: 3 },
    { id: 'plate', categoryId: 'grade-product', label: '후판', order: 4 },
    { id: 'new-investment', categoryId: 'investment-project', label: '신규 투자', order: 1 },
    { id: 'government-project', categoryId: 'investment-project', label: '국책 과제', order: 2 },
    { id: 'joint-research', categoryId: 'investment-project', label: '공동 연구', order: 3 },
    { id: 'budget-schedule', categoryId: 'investment-project', label: '예산/일정', order: 4 },
    { id: 'test-equipment', categoryId: 'equipment-test', label: '시험 장비', order: 1 },
    { id: 'analysis-request', categoryId: 'equipment-test', label: '분석 의뢰', order: 2 },
    { id: 'pilot', categoryId: 'equipment-test', label: 'Pilot', order: 3 },
    { id: 'safety-inspection', categoryId: 'equipment-test', label: '안전/점검', order: 4 },
    { id: 'operation-standard', categoryId: 'system-operation', label: '운영 기준', order: 1 },
    { id: 'approval-review', categoryId: 'system-operation', label: '심의/승인', order: 2 },
    { id: 'data-security', categoryId: 'system-operation', label: '데이터/보안', order: 3 },
    { id: 'collaboration-process', categoryId: 'system-operation', label: '협업 프로세스', order: 4 },
  ],
  issueGroups: [
    {
      id: 'issue-sts-430-surface',
      title: 'STS-430 표면 결함 재발',
      categoryId: 'grade-product',
      subtopicId: 'sts',
      status: 'resolved',
      statusSource: 'manual',
      firstOccurredAt: '2026-01-01',
      latestUpdatedAt: '2026-02-04',
      currentSummary: '공정 조건 조정 후 2차 샘플에서 재발 없음',
      tags: ['STS-430', '표면결함', '열처리', '고객A'],
      groupLabel: '표면결함개선',
      groupColorTone: 'teal',
      ownerName: '김연구',
      ownerResearchGroup: '표면품질연구그룹',
      relatedDepartment: '냉연품질보증섹션',
      priorityLabel: '보통',
      sensitive: true,
      archived: false,
    },
    {
      id: 'issue-sts-corrosion-test',
      title: 'STS 내식성 시험 조건 이슈',
      categoryId: 'grade-product',
      subtopicId: 'sts',
      status: 'cause_review',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-11',
      latestUpdatedAt: '2026-06-20',
      currentSummary: '시험 조건 편차 원인 검토 중',
      tags: ['STS', '내식성', '시험조건'],
      groupLabel: '시험조건',
      groupColorTone: 'neutral',
      ownerName: '박연구',
      ownerResearchGroup: '스테인리스솔루션그룹',
      relatedDepartment: '분석시험센터',
      priorityLabel: '보통',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-hpf-forming-delay',
      title: 'HPF 성형 조건 검증 지연',
      categoryId: 'grade-product',
      subtopicId: 'hpf',
      status: 'actioning',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-03',
      latestUpdatedAt: '2026-06-24',
      currentSummary: '추가 샘플 확보 후 재검증 예정',
      tags: ['HPF', '성형', '검증'],
      groupLabel: '성형조건',
      groupColorTone: 'green',
      ownerName: '이연구',
      ownerResearchGroup: '성형공정연구그룹',
      relatedDepartment: '열성형기술섹션',
      priorityLabel: '높음',
      sensitive: false,
      archived: false,
    },
    {
      id: 'issue-operation-approval-delay',
      title: '공동연구 샘플 반출 승인 지연',
      categoryId: 'system-operation',
      subtopicId: 'approval-review',
      status: 'actioning',
      statusSource: 'auto',
      firstOccurredAt: '2026-06-14',
      latestUpdatedAt: '2026-06-21',
      currentSummary: '부서 간 승인 책임 구간 재정의 진행 중',
      tags: ['승인', '공동연구', '샘플반출'],
      groupLabel: '승인흐름',
      groupColorTone: 'neutral',
      ownerName: '정연구',
      ownerResearchGroup: '연구운영기획그룹',
      relatedDepartment: '법무/보안검토파트',
      priorityLabel: '높음',
      sensitive: false,
      archived: false,
    },
  ],
  detailIssues: [
    {
      id: 'detail-sts-430-rolling-recur',
      issueGroupId: 'issue-sts-430-surface',
      title: '압연 조건 변경 후 재발 확인',
      status: 'resolved',
      firstOccurredAt: '2026-01-01',
      latestUpdatedAt: '2026-02-04',
      currentSummary: '조건 조정 후 2차 샘플에서 재발 없음',
      tags: ['압연조건', '재발확인'],
      relatedEquipment: '열연 #2',
      relatedCustomer: '고객A',
      priorityLabel: '보통',
      ownerName: '김연구',
      ownerResearchGroup: '표면품질연구그룹',
      relatedDepartment: '냉연품질보증섹션',
      completedAt: '2026-02-04',
      completionNote: '최종 조건 조정 후 재발 없음 확인',
      archived: false,
    },
    {
      id: 'detail-sts-corrosion-test-condition',
      issueGroupId: 'issue-sts-corrosion-test',
      title: '염수 분무 조건 편차 확인',
      status: 'cause_review',
      firstOccurredAt: '2026-06-20',
      latestUpdatedAt: '2026-06-20',
      currentSummary: '시편 준비 조건과 장비 설정값 비교 중',
      tags: ['시험조건', '내식성'],
      ownerName: '박연구',
      ownerResearchGroup: '스테인리스솔루션그룹',
      relatedDepartment: '분석시험센터',
      priorityLabel: '보통',
      needsReview: false,
      archived: false,
    },
    {
      id: 'detail-operation-approval-role',
      issueGroupId: 'issue-operation-approval-delay',
      title: '샘플 반출 승인 책임 구간 불명확',
      status: 'actioning',
      firstOccurredAt: '2026-06-14',
      latestUpdatedAt: '2026-06-21',
      currentSummary: '승인 책임과 보안 검토 선후 관계 조정 중',
      tags: ['승인', '보안검토'],
      priorityLabel: '높음',
      ownerName: '정연구',
      ownerResearchGroup: '연구운영기획그룹',
      relatedDepartment: '법무/보안검토파트',
      needsReview: true,
      archived: false,
    },
  ],
  historyEntries: [
    {
      id: 'hist-sts-430-occurred',
      issueGroupId: 'issue-sts-430-surface',
      detailIssueId: 'detail-sts-430-rolling-recur',
      date: '2026-01-01',
      status: 'occurred',
      changesDetailIssueStatus: true,
      summary: '고객 클레임 접수',
      details: 'STS-430 적용 제품에서 표면 결함 재발 클레임이 접수되었다.',
      remainingRisk: '발생 범위와 재현 조건 확인 필요',
      nextCheckDate: '2026-01-10',
      blockName: '발생 및 접수',
      referenceLinks: [],
      createdAt: '2026-01-01T09:00:00+09:00',
      updatedAt: '2026-01-01T09:00:00+09:00',
    },
    {
      id: 'hist-sts-430-cause',
      issueGroupId: 'issue-sts-430-surface',
      detailIssueId: 'detail-sts-430-rolling-recur',
      date: '2026-01-10',
      status: 'cause_review',
      changesDetailIssueStatus: true,
      summary: '열처리 이력 및 과거 사례 확인',
      details: '동일 강종 과거 사례와 열처리 조건 이력을 대조했다.',
      remainingRisk: '압연 조건 영향 여부 추가 확인 필요',
      nextCheckDate: '2026-01-22',
      blockName: '원인검토',
      referenceLinks: [],
      createdAt: '2026-01-10T10:00:00+09:00',
      updatedAt: '2026-01-10T10:00:00+09:00',
    },
    {
      id: 'hist-sts-430-action',
      issueGroupId: 'issue-sts-430-surface',
      detailIssueId: 'detail-sts-430-rolling-recur',
      date: '2026-01-22',
      status: 'actioning',
      changesDetailIssueStatus: true,
      summary: '임시 조건 조정, 2차 샘플 대기',
      details: '공정 조건을 임시 조정하고 2차 샘플 결과를 기다린다.',
      remainingRisk: '2차 샘플에서 재발 시 추가 조건 변경 필요',
      nextCheckDate: '2026-02-04',
      blockName: '조치 및 검증',
      referenceLinks: [],
      createdAt: '2026-01-22T14:00:00+09:00',
      updatedAt: '2026-01-22T14:00:00+09:00',
    },
    {
      id: 'hist-sts-430-resolved',
      issueGroupId: 'issue-sts-430-surface',
      detailIssueId: 'detail-sts-430-rolling-recur',
      date: '2026-02-04',
      status: 'resolved',
      changesDetailIssueStatus: true,
      summary: '최종 조건 조정 후 재발 없음',
      details: '최종 조건 조정 후 2차 샘플에서 표면 결함 재발이 확인되지 않았다.',
      remainingRisk: '양산 적용 초기 모니터링 필요',
      blockName: '조치 및 검증',
      referenceLinks: [],
      createdAt: '2026-02-04T16:00:00+09:00',
      updatedAt: '2026-02-04T16:00:00+09:00',
    },
    {
      id: 'hist-sts-corrosion-review',
      issueGroupId: 'issue-sts-corrosion-test',
      detailIssueId: 'detail-sts-corrosion-test-condition',
      date: '2026-06-20',
      status: 'cause_review',
      changesDetailIssueStatus: true,
      summary: '시험 조건 편차 원인 검토',
      details: '시편 준비 조건과 시험 장비 설정값을 비교하고 있다.',
      remainingRisk: '동일 조건 반복 시험 필요',
      nextCheckDate: '2026-06-28',
      blockName: '원인검토',
      referenceLinks: ['https://poslab.example/reports/sts-corrosion-test-condition'],
      createdAt: '2026-06-20T11:00:00+09:00',
      updatedAt: '2026-06-20T11:00:00+09:00',
    },
    {
      id: 'hist-operation-approval-delay',
      issueGroupId: 'issue-operation-approval-delay',
      detailIssueId: 'detail-operation-approval-role',
      date: '2026-06-21',
      status: 'actioning',
      changesDetailIssueStatus: true,
      summary: '승인 책임 구간 재정의 진행',
      details: '공동연구 샘플 반출 건에서 연구부서, 보안 검토, 법무 검토의 승인 순서가 중복되어 처리 기간이 길어졌다.',
      remainingRisk: '긴급 반출 건에서 동일 지연이 반복될 수 있음',
      nextCheckDate: '2026-06-27',
      blockName: '조치 및 검증',
      referenceLinks: [],
      authorName: '정연구',
      createdAt: '2026-06-21T15:00:00+09:00',
      updatedAt: '2026-06-21T15:00:00+09:00',
    },
  ],
};
